#!/usr/bin/env python3
"""
Dynamic inventory script for RKE2 HA cluster.

Reads inventory/inventory.json generated by Terraform and outputs
an Ansible-compatible inventory JSON, automatically configuring:
  - SSH ProxyCommand for private-subnet nodes (via bastion)
  - Per-host SSH key path
  - Group structure: bastion, control_plane_init, control_plane_join,
    control_plane, workers, k8s_nodes
"""

import json
import os
import sys


def load_terraform_inventory():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    inv_path = os.path.join(script_dir, "..", "inventory", "inventory.json")
    with open(inv_path) as f:
        return json.load(f)


def build_ansible_inventory(tf_inv):
    bastion_public_ip  = tf_inv["nginx_lb"]["public_ip"]
    bastion_private_ip = tf_inv["nginx_lb"]["private_ip"]
    control_planes     = tf_inv["control_plane"]
    workers            = tf_inv["workers"]
    ssh_key            = tf_inv["ssh_key"]
    rke2_version       = tf_inv["rke2_version"]

    cp_init = [control_planes[0]]
    cp_join = control_planes[1:]

    # ProxyCommand used by every private-subnet node
    proxy_cmd = (
        f"ssh -W %h:%p -i {ssh_key} "
        f"-o StrictHostKeyChecking=no "
        f"ubuntu@{bastion_public_ip}"
    )
    private_ssh_args = f"-o ProxyCommand='{proxy_cmd}' -o StrictHostKeyChecking=no"

    # Common vars injected into every host so roles can reference them directly
    common_vars = {
        "lb_private_ip": bastion_private_ip,
        "lb_public_ip":  bastion_public_ip,
        "rke2_version":  rke2_version,
    }

    hostvars = {}

    # Bastion — reachable directly from the internet
    hostvars[bastion_public_ip] = {
        "ansible_host":                bastion_public_ip,
        "ansible_user":                "ubuntu",
        "ansible_ssh_private_key_file": ssh_key,
        "ansible_ssh_common_args":     "-o StrictHostKeyChecking=no",
        **common_vars,
    }

    # Control plane and worker nodes — reached through bastion ProxyCommand
    for ip in control_planes + workers:
        hostvars[ip] = {
            "ansible_host":                ip,
            "ansible_user":                "ubuntu",
            "ansible_ssh_private_key_file": ssh_key,
            "ansible_ssh_common_args":     private_ssh_args,
            **common_vars,
        }

    inventory = {
        # ── individual host groups ──────────────────────────────────────────
        "bastion": {
            "hosts": [bastion_public_ip],
        },
        "control_plane_init": {      # first CP — bootstraps the cluster
            "hosts": cp_init,
        },
        "control_plane_join": {      # remaining CPs — join the existing cluster
            "hosts": cp_join,
        },
        "workers": {
            "hosts": workers,
        },
        # ── composite groups ────────────────────────────────────────────────
        "control_plane": {
            "children": ["control_plane_init", "control_plane_join"],
        },
        "k8s_nodes": {               # all nodes that need common preparation
            "children": ["control_plane", "workers"],
        },
        # ── per-host variables ──────────────────────────────────────────────
        "_meta": {
            "hostvars": hostvars,
        },
    }

    return inventory


def main():
    tf_inv  = load_terraform_inventory()
    ansible = build_ansible_inventory(tf_inv)
    print(json.dumps(ansible, indent=2))


if __name__ == "__main__":
    main()
